/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-22 23:41:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.ProductDAO;
import Model.Cart;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.Cart");
    _jspx_imports_classes.add("DAO.ProductDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<Cart> cart_list = (ArrayList<Cart>) session.getAttribute("cart-list");
List<Cart> cartproduct = null;
if(cart_list != null){
	ProductDAO dao = new ProductDAO();
	cartproduct = dao.getCartProducts(cart_list);
	Double total = dao.getTotalCart(cart_list);
	request.setAttribute("cart_list", cart_list);
	request.setAttribute("total", total);
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Coffee luck-Cart</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("              <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("     <!-- Start Top Nav -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\" id=\"templatemo_nav_top\">\r\n");
      out.write("        <div class=\"container text-light\">\r\n");
      out.write("            <div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <i class=\"fa fa-envelope mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("                      href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                    <i class=\"fa fa-phone mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://fb.com/templatemo\" target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("                          class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("            <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("                <div class=\"input-group mb-2\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                    <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"bg-success py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-5\">\r\n");
      out.write("                <div class=\"col-md-8 text-white\">\r\n");
      out.write("                    <h1>Cart</h1>\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Close Banner -->\r\n");
      out.write("<br><h3 class=\"text-center\">List of Cart</h3>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write(" <a href=\"XuLyRemoveAllFromCart\"><button class=\"btn btn-black btn-lg py-3 btn-block\" ><span style=\"font-size:26px\">Remove all</span></button></a>\r\n");
      out.write("\r\n");
      out.write("<div class=\"untree_co-section before-footer-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("            <form class=\"col-md-12\" method=\"post\">\r\n");
      out.write("                <div class=\"site-blocks-table\">\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"product-order\">STT</th> \r\n");
      out.write("                                <th class=\"product-thumbnail\">Image</th>\r\n");
      out.write("                                <th class=\"product-name\">Product</th>\r\n");
      out.write("                                <th class=\"product-price\">Price</th>\r\n");
      out.write("                                <th class=\"product-quantity\">Quantity</th>\r\n");
      out.write("                                <th class=\"product-total\">Total</th>\r\n");
      out.write("                                <th class=\"product-remove\">Remove</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");

                                int orderNumber = 1; // Initialize order counter

                                
if (cart_list != null) {
                                    for (Cart c : cartproduct) {
                            
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td class=\"product-order\">");
      out.print( orderNumber++ );
      out.write("</td> <td class=\"product-thumbnail\">\r\n");
      out.write("                                    <img src=\"");
      out.print(c.getImage() );
      out.write("\" alt=\"Image\" class=\"img-fluid\" style=\"width:100px;height:100px\">\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td class=\"product-name\">\r\n");
      out.write("                                    <h2 class=\"h5 text-black\">");
      out.print(c.getId() );
      out.write("</h2>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>");
      out.print(c.getPrice() / c.getQuantity() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"form-group d-flex justify-content-between\">\r\n");
      out.write("                                        <a class=\"btn bnt-sm btn-incre\" href=\"XuLyIncDec?action=dec&id=");
      out.print(c.getId());
      out.write("\"><i class=\"fas fa-minus-square\"></i></a>\r\n");
      out.write("                                        <input type=\"text\" name=\"quantity\" class=\"form-control\"  value=\"");
      out.print(c.getQuantity());
      out.write("\" readonly>\r\n");
      out.write("                                        <a class=\"btn btn-sm btn-decre\" href=\"XuLyIncDec?action=inc&id=");
      out.print(c.getId());
      out.write("\"><i class=\"fas fa-plus-square\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>");
      out.print(c.getPrice() );
      out.write("</td>\r\n");
      out.write("                                <td><a href=\"XuLyRemoveFromCart?id=");
      out.print(c.getId() );
      out.write("\" class=\"btn btn-black btn-sm\">X</a></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            ");

                                    }
                                }
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                  <div class=\"row mb-5\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                      <button onclick=\"event.preventDefault(); window.location.href='XuLyProduct';\" class=\"btn btn-outline-black btn-sm btn-block\">Continue Shopping</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 pl-5\">\r\n");
      out.write("                  <div class=\"row justify-content-end\">\r\n");
      out.write("                    <div class=\"col-md-7\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 text-right border-bottom mb-5\">\r\n");
      out.write("                          <h3 class=\"text-black h4 text-uppercase\">Cart Totals</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"row mb-5\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                          <span class=\"text-black\">Total</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 text-right\">\r\n");
      out.write("                          <strong class=\"text-black\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("        \r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                          <a href=\"XuLyCheckOut\"><button class=\"btn btn-black btn-lg py-3 btn-block\" >Proceed To Checkout</button></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Footer -->\r\n");
      out.write("    <footer class=\"bg-dark\" id=\"tempaltemo_footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">Zay Shop</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\r\n");
      out.write("                            123 Consectetur at ligula 10660\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-phone fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Products</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Luxury</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Wear</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Men's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Women's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Popular Dress</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Gym Accessories</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Shoes</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Further Info</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Home</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">About Us</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Shop Locations</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">FAQs</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row text-light mb-4\">\r\n");
      out.write("                <div class=\"col-12 mb-3\">\r\n");
      out.write("                    <div class=\"w-100 my-3 border-top border-light\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto me-auto\">\r\n");
      out.write("                    <ul class=\"list-inline text-left footer-icons\">\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a rel=\"nofollow\" class=\"text-light text-decoration-none\" target=\"_blank\" href=\"http://fb.com/templatemo\"><i class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://twitter.com/\"><i class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.linkedin.com/\"><i class=\"fab fa-linkedin fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto\">\r\n");
      out.write("                    <label class=\"sr-only\" for=\"subscribeEmail\">Email address</label>\r\n");
      out.write("                    <div class=\"input-group mb-2\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-dark border-light\" id=\"subscribeEmail\" placeholder=\"Email address\">\r\n");
      out.write("                        <div class=\"input-group-text btn-success text-light\">Subscribe</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"w-100 bg-black py-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row pt-2\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <p class=\"text-left text-light\">\r\n");
      out.write("                            Copyright &copy; 2021 Company Name \r\n");
      out.write("                            | Designed by <a rel=\"sponsored\" href=\"https://templatemo.com/page/1\" target=\"_blank\">TemplateMo</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Web/cart.jsp(70,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName == 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/Web/cart.jsp(74,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName != 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
