/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-22 14:23:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.NgonNguDAO;
import java.util.*;

public final class shop_002dsingle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.NgonNguDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Map<String,String> showlanguage = new NgonNguDAO().vietnamLanguage();
   String lang = (String) session.getAttribute("lang");
   if(lang!=null){
	   if(lang.equals("Vietnamese")){
		   showlanguage = new NgonNguDAO().vietnamLanguage();
	   }else if(lang.equals("English")){
		   showlanguage = new NgonNguDAO().englishLanguage();
		   
	   }
   }


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shop-Detail</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("          <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("   <div id=\"fb-root\"></div>\r\n");
      out.write("<script async defer crossorigin=\"anonymous\" src=\"https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v18.0&appId=1986721085041576\" nonce=\"cL2uF67Y\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      DAO.ProductDAO product = null;
      product = (DAO.ProductDAO) _jspx_page_context.getAttribute("product", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (product == null){
        product = new DAO.ProductDAO();
        _jspx_page_context.setAttribute("product", product, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Start Top Nav -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\" id=\"templatemo_nav_top\">\r\n");
      out.write("        <div class=\"container text-light\">\r\n");
      out.write("            <div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <i class=\"fa fa-envelope mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("                      href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                    <i class=\"fa fa-phone mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://fb.com/templatemo\" target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("                          class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a role=\"menuitem\" href=\"XuLyDetailProduct?lang=Vietnamese&productid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"assets/img/vietnam.png\" style=\"position:absolute;left:1140px;top:7px\"></a>\r\n");
      out.write("<a role=\"menuitem\" href=\"XuLyDetailProductE?lang=English&productid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"assets/img/united-states.png\" style=\"position:absolute;left:1180px;top:7px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("            <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("                <div class=\"input-group mb-2\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                    <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Open Content -->\r\n");
      out.write("    <section class=\"bg-light\">\r\n");
      out.write("        <div class=\"container pb-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-5 mt-5\">\r\n");
      out.write("                    <div class=\"card mb-3\">\r\n");
      out.write("                        <img class=\"card-img img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Card image cap\" id=\"product-detail\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" download=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.proname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"  text-align: center;\r\n");
      out.write("                        \"><button  class=\"btn btn-success btn-lg\" style=\"align-item:center\"><i class=\"fas fa-download\"></i>\r\n");
      out.write("                        </button></a>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!--Start Controls-->\r\n");
      out.write("                        <div class=\"col-1 align-self-center\">\r\n");
      out.write("                            <a href=\"#multi-item-example\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("                                <i class=\"text-dark fas fa-chevron-left\"></i>\r\n");
      out.write("                                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--End Controls-->\r\n");
      out.write("                        <!--Start Carousel Wrapper-->\r\n");
      out.write("                        <div id=\"multi-item-example\" class=\"col-10 carousel slide carousel-multi-item\" data-bs-ride=\"carousel\">\r\n");
      out.write("                            <!--Start Slides-->\r\n");
      out.write("                            <div class=\"carousel-inner product-links-wap\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("                                <!--First slide-->\r\n");
      out.write("                                <div class=\"carousel-item active\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Coffee10caramel.jpg\" alt=\"Product Image 1\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/MilkTea10.jpg\" alt=\"Product Image 2\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Juice10.jpg\" alt=\"Product Image 3\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--/.First slide-->\r\n");
      out.write("\r\n");
      out.write("                                <!--Second slide-->\r\n");
      out.write("                                <div class=\"carousel-item\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Coffee10caramel.jpg\" alt=\"Product Image 1\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/MilkTea10.jpg\" alt=\"Product Image 2\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Juice10.jpg\" alt=\"Product Image 3\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--/.Second slide-->\r\n");
      out.write("\r\n");
      out.write("                                <!--Third slide-->\r\n");
      out.write("                                <div class=\"carousel-item\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                           <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Coffee10caramel.jpg\" alt=\"Product Image 1\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/MilkTea10.jpg\" alt=\"Product Image 2\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-4\">\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <img class=\"card-img img-fluid\" src=\"assets/img/Juice10.jpg\" alt=\"Product Image 3\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--/.Third slide-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--End Slides-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--End Carousel Wrapper-->\r\n");
      out.write("                        <!--Start Controls-->\r\n");
      out.write("                        <div class=\"col-1 align-self-center\">\r\n");
      out.write("                            <a href=\"#multi-item-example\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("                                <i class=\"text-dark fas fa-chevron-right\"></i>\r\n");
      out.write("                                <span class=\"sr-only\">Next</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--End Controls-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- col end -->\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"col-lg-7 mt-5\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h1 class=\"h2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.getProname()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                            <p class=\"h3 py-2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                            <p class=\"py-2\">\r\n");
      out.write("                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star text-secondary\"></i>\r\n");
      out.write("                                <span class=\"list-inline-item text-dark\">Rating 4.8 | ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailsize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Comments</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <ul class=\"list-inline\">\r\n");
      out.write("                                <li class=\"list-inline-item\">\r\n");
      out.write("                                    <h6>Brand:</h6>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item\">\r\n");
      out.write("                                    <p class=\"text-muted\"><strong>VietNam's Coffee</strong></p>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                            <h6>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.descriptions}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\r\n");
      out.write("                            \r\n");
      out.write("                                \r\n");
      out.write("                                  \r\n");
      out.write("                                \r\n");
      out.write("                                 \r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                         \r\n");
      out.write("                                <input type=\"hidden\" name=\"product-title\" value=\"Activewear\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row pb-3\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"col d-grid\">\r\n");
      out.write("                                        <a href=\"XuLyProduct\"><button type=\"submit\" class=\"btn btn-success btn-lg\" name=\"submit\" value=\"addtocard\">GO BACK TO SHOP</button></a>\r\n");
      out.write("                                       \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            <form action=\"XuLyDetailComment\" method=\"post\">\r\n");
      out.write("                            ProductId: <input type=\"text\" name = \"pid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <br>\r\n");
      out.write("                            Comment: <textarea name=\"comment\" style=\"width:620px;height:100px\"></textarea>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-success\">Post</button>\r\n");
      out.write("                            \r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fb-comments\" data-href=\"http://localhost:8080/DoAnWeb/XuLyProduct\" data-width=\"10\" data-numposts=\"5\"></div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Close Content -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Article -->\r\n");
      out.write("    <!-- <section class=\"py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row text-left p-2 pb-3\">\r\n");
      out.write("                <h4>Related Products</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            Start Carousel Wrapper\r\n");
      out.write("            <div id=\"carousel-related-product\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_08.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Red Clothing</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$20.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_09.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">White Shirt</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$25.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_10.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$45.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_11.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Black Fashion</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$60.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_08.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li class=\"\">M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$80.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_09.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$110.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_10.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$125.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_11.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$160.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_08.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$180.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_09.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$220.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_10.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"p-2 pb-3\">\r\n");
      out.write("                    <div class=\"product-wap card rounded-0\">\r\n");
      out.write("                        <div class=\"card rounded-0\">\r\n");
      out.write("                            <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_11.jpg\">\r\n");
      out.write("                            <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <ul class=\"list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                    <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                            <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                <li>M/L/X/XL</li>\r\n");
      out.write("                                <li class=\"pt-2\">\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                    <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p class=\"text-center mb-0\">$300.00</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> -->\r\n");
      out.write("    <!-- End Article -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Footer -->\r\n");
      out.write("    <footer class=\"bg-dark\" id=\"tempaltemo_footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">Zay Shop</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\r\n");
      out.write("                            123 Consectetur at ligula 10660\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-phone fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Products</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Luxury</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Wear</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Men's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Women's Shoes</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Popular Dress</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Gym Accessories</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Sport Shoes</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Further Info</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Home</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">About Us</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Shop Locations</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">FAQs</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row text-light mb-4\">\r\n");
      out.write("                <div class=\"col-12 mb-3\">\r\n");
      out.write("                    <div class=\"w-100 my-3 border-top border-light\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto me-auto\">\r\n");
      out.write("                    <ul class=\"list-inline text-left footer-icons\">\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"http://facebook.com/\"><i class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://twitter.com/\"><i class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("                            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.linkedin.com/\"><i class=\"fab fa-linkedin fa-lg fa-fw\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto\">\r\n");
      out.write("                    <label class=\"sr-only\" for=\"subscribeEmail\">Email address</label>\r\n");
      out.write("                    <div class=\"input-group mb-2\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-dark border-light\" id=\"subscribeEmail\" placeholder=\"Email address\">\r\n");
      out.write("                        <div class=\"input-group-text btn-success text-light\">Subscribe</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"w-100 bg-black py-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row pt-2\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <p class=\"text-left text-light\">\r\n");
      out.write("                            Copyright &copy; 2021 Company Name \r\n");
      out.write("                            | Designed by <a rel=\"sponsored\" href=\"https://templatemo.com\" target=\"_blank\">TemplateMo</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Slider Script -->\r\n");
      out.write("    <script src=\"assets/js/slick.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $('#carousel-related-product').slick({\r\n");
      out.write("            infinite: true,\r\n");
      out.write("            arrows: false,\r\n");
      out.write("            slidesToShow: 4,\r\n");
      out.write("            slidesToScroll: 3,\r\n");
      out.write("            dots: true,\r\n");
      out.write("            responsive: [{\r\n");
      out.write("                    breakpoint: 1024,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 3,\r\n");
      out.write("                        slidesToScroll: 3\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    breakpoint: 600,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 2,\r\n");
      out.write("                        slidesToScroll: 3\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    breakpoint: 480,\r\n");
      out.write("                    settings: {\r\n");
      out.write("                        slidesToShow: 2,\r\n");
      out.write("                        slidesToScroll: 3\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            ]\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- End Slider Script -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/Web/shop-single.jsp(42,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("pi");
      // /WEB-INF/Web/shop-single.jsp(42,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/shop-single.jsp(42,4) '${product.getAllProductById(param.productid)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${product.getAllProductById(param.productid)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Web/shop-single.jsp(76,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName == 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/Web/shop-single.jsp(80,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName != 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
