/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-29 03:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Product;
import java.util.List;
import Model.ShoppingCart;
import DAO.GioHangDAO;
import DAO.NgonNguDAO;
import java.util.*;

public final class Shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.Product");
    _jspx_imports_classes.add("DAO.GioHangDAO");
    _jspx_imports_classes.add("Model.ShoppingCart");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("DAO.NgonNguDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Map<String,String> showlanguage = new NgonNguDAO().vietnamLanguage();
   String lang = (String) session.getAttribute("lang");
   if(lang!=null){
	   if(lang.equals("Vietnamese")){
		   showlanguage = new NgonNguDAO().vietnamLanguage();
	   }else if(lang.equals("English")){
		   showlanguage = new NgonNguDAO().englishLanguage();
		   
	   }
   }


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shop</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Top Nav -->\r\n");
      out.write("	");
      DAO.ProductDAO product = null;
      product = (DAO.ProductDAO) _jspx_page_context.getAttribute("product", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (product == null){
        product = new DAO.ProductDAO();
        _jspx_page_context.setAttribute("product", product, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      DAO.CategoryDAO category = null;
      category = (DAO.CategoryDAO) _jspx_page_context.getAttribute("category", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (category == null){
        category = new DAO.CategoryDAO();
        _jspx_page_context.setAttribute("category", category, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Top Nav -->\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\"\r\n");
      out.write("		id=\"templatemo_nav_top\">\r\n");
      out.write("		<div class=\"container text-light\">\r\n");
      out.write("			<div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<i class=\"fa fa-envelope mx-2\"></i> <a\r\n");
      out.write("						class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("						href=\"mailto:info@company.com\">info@company.com</a> <i\r\n");
      out.write("						class=\"fa fa-phone mx-2\"></i> <a\r\n");
      out.write("						class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("						href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<a class=\"text-light\" href=\"https://fb.com/templatemo\"\r\n");
      out.write("						target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("						class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a> <a\r\n");
      out.write("						class=\"text-light\" href=\"https://www.instagram.com/\"\r\n");
      out.write("						target=\"_blank\"><i class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("					<a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("						class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a> <a class=\"text-light\"\r\n");
      out.write("						href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("						class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<a role=\"menuitem\" href=\"XuLyProduct?lang=Vietnam\"><img\r\n");
      out.write("					src=\"assets/img/vietnam.png\"\r\n");
      out.write("					style=\"position: absolute; left: 1140px; top: 7px\"></a> <a\r\n");
      out.write("					role=\"menuitem\" href=\"XuLyProductE?lang=English\"><img\r\n");
      out.write("					src=\"assets/img/united-states.png\"\r\n");
      out.write("					style=\"position: absolute; left: 1180px; top: 7px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- Close Header -->\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("			<div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("				<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"XuLySearch\" method=\"get\"\r\n");
      out.write("				class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"input-group mb-2\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" id=\"inputModalSearch\"\r\n");
      out.write("						name=\"search\" placeholder=\"Search ...\" list=\"datalist1\">\r\n");
      out.write("					<datalist id=\"datalist1\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</datalist>\r\n");
      out.write("					<button type=\"submit\"\r\n");
      out.write("						class=\"input-group-text bg-success text-light\">\r\n");
      out.write("						<i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Start Hero Section -->\r\n");
      out.write("	<section class=\"bg-success py-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center py-5\">\r\n");
      out.write("				<div class=\"col-md-8 text-white\">\r\n");
      out.write("					<h1>Shop</h1>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Hero Section -->\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<!-- Start Content -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container py-5\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-3\">\r\n");
      out.write("				<h1 class=\"h2 pb-4\">Categories</h1>\r\n");
      out.write("				<ul class=\"list-unstyled templatemo-accordion\">\r\n");
      out.write("\r\n");
      out.write("					<li class=\"pb-3\"><a\r\n");
      out.write("						class=\"collapsed d-flex justify-content-between h3 text-decoration-none\"\r\n");
      out.write("						href=\"#\" onclick=\"toggleList1('collapseThree1')\"> Feature <i\r\n");
      out.write("							class=\"pull-right fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul id=\"collapseThree1\" class=\"collapse list-unstyled pl-3\">\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyProduct\">Normal</a></li>\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyAtoZProduct\">A\r\n");
      out.write("									to Z</a></li>\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyZtoAProduct\">Z\r\n");
      out.write("									to A</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"pb-3\"><a\r\n");
      out.write("						class=\"collapsed d-flex justify-content-between h3 text-decoration-none\"\r\n");
      out.write("						href=\"#\" onclick=\"toggleList2('collapseThree2')\"> Product <i\r\n");
      out.write("							class=\"pull-right fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul id=\"collapseThree2\" class=\"collapse list-unstyled pl-3\">\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyProduct\">All</a></li>\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					<li class=\"pb-3\"><a\r\n");
      out.write("						class=\"collapsed d-flex justify-content-between h3 text-decoration-none\"\r\n");
      out.write("						href=\"#\" onclick=\"toggleList1('collapseThree1')\"> Price <i\r\n");
      out.write("							class=\"pull-right fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul id=\"collapseThree1\" class=\"collapse list-unstyled pl-3\">\r\n");
      out.write("\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyPrice1\">0\r\n");
      out.write("									to 50.00</a></li>\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyPrice2\">50.00\r\n");
      out.write("									to 100.00</a></li>\r\n");
      out.write("							<li><a class=\"text-decoration-none\" href=\"XuLyPrice3\">100.00\r\n");
      out.write("									to 500.00</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("					<br><br>\r\n");
      out.write("            <a href=\"XuLyComment?username=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button type=\"submit\" class=\"btn btn-success btn-lg\" name=\"submit\">Your Comment</button></a>\r\n");
      out.write("			 \r\n");
      out.write("			</div>\r\n");
      out.write("            \r\n");
      out.write("			<div class=\"col-lg-9\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<button onclick=\"topFunction()\" id=\"myBtn\" title=\"Go to top\">TOP</button>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- End Content -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Brands -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Footer -->\r\n");
      out.write("	<footer class=\"bg-dark\" id=\"tempaltemo_footer\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-4 pt-5\">\r\n");
      out.write("					<h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">Zay\r\n");
      out.write("						Shop</h2>\r\n");
      out.write("					<ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("						<li><i class=\"fas fa-map-marker-alt fa-fw\"></i> 123\r\n");
      out.write("							Consectetur at ligula 10660</li>\r\n");
      out.write("						<li><i class=\"fa fa-phone fa-fw\"></i> <a\r\n");
      out.write("							class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><i class=\"fa fa-envelope fa-fw\"></i> <a\r\n");
      out.write("							class=\"text-decoration-none\" href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-4 pt-5\">\r\n");
      out.write("					<h2 class=\"h2 text-light border-bottom pb-3 border-light\">Products</h2>\r\n");
      out.write("					<ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Luxury</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Sport Wear</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Men's Shoes</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Women's\r\n");
      out.write("								Shoes</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Popular\r\n");
      out.write("								Dress</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Gym\r\n");
      out.write("								Accessories</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Sport Shoes</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-4 pt-5\">\r\n");
      out.write("					<h2 class=\"h2 text-light border-bottom pb-3 border-light\">Further\r\n");
      out.write("						Info</h2>\r\n");
      out.write("					<ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Home</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">About Us</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Shop\r\n");
      out.write("								Locations</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">FAQs</a></li>\r\n");
      out.write("						<li><a class=\"text-decoration-none\" href=\"#\">Contact</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row text-light mb-4\">\r\n");
      out.write("				<div class=\"col-12 mb-3\">\r\n");
      out.write("					<div class=\"w-100 my-3 border-top border-light\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto me-auto\">\r\n");
      out.write("					<ul class=\"list-inline text-left footer-icons\">\r\n");
      out.write("						<li\r\n");
      out.write("							class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("							<a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("							href=\"http://facebook.com/\"><i\r\n");
      out.write("								class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li\r\n");
      out.write("							class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("							<a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("							href=\"https://www.instagram.com/\"><i\r\n");
      out.write("								class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li\r\n");
      out.write("							class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("							<a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("							href=\"https://twitter.com/\"><i\r\n");
      out.write("								class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li\r\n");
      out.write("							class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("							<a class=\"text-light text-decoration-none\" target=\"_blank\"\r\n");
      out.write("							href=\"https://www.linkedin.com/\"><i\r\n");
      out.write("								class=\"fab fa-linkedin fa-lg fa-fw\"></i></a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto\">\r\n");
      out.write("					<label class=\"sr-only\" for=\"subscribeEmail\">Email address</label>\r\n");
      out.write("					<div class=\"input-group mb-2\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control bg-dark border-light\"\r\n");
      out.write("							id=\"subscribeEmail\" placeholder=\"Email address\">\r\n");
      out.write("						<div class=\"input-group-text btn-success text-light\">Subscribe</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"w-100 bg-black py-3\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row pt-2\">\r\n");
      out.write("					<div class=\"col-12\">\r\n");
      out.write("						<p class=\"text-left text-light\">\r\n");
      out.write("							Copyright &copy; 2021 Company Name | Designed by <a\r\n");
      out.write("								rel=\"sponsored\" href=\"https://templatemo.com\" target=\"_blank\">TemplateMo</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Script -->\r\n");
      out.write("	<script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    function buy(id){\r\n");
      out.write("    	document.f.action=\"buy?id=\" + id;\r\n");
      out.write("    	document.f.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function toggleList1(listId1) {\r\n");
      out.write("    	  const list1 = document.getElementById(listId1);\r\n");
      out.write("    	  const isOpen1 = list.classList.contains(\"show1\");\r\n");
      out.write("\r\n");
      out.write("    	  if (isOpen1) {\r\n");
      out.write("    	    list1.classList.remove(\"show1\");\r\n");
      out.write("    	  } else {\r\n");
      out.write("    	    list1.classList.add(\"show1\");\r\n");
      out.write("    	  }\r\n");
      out.write("    	}\r\n");
      out.write("    function toggleList2(listId2) {\r\n");
      out.write("    	  const list2 = document.getElementById(listId2);\r\n");
      out.write("    	  const isOpen2 = list.classList.contains(\"show2\");\r\n");
      out.write("\r\n");
      out.write("    	  if (isOpen2) {\r\n");
      out.write("    	    list2.classList.remove(\"show2\");\r\n");
      out.write("    	  } else {\r\n");
      out.write("    	    list2.classList.add(\"show2\");\r\n");
      out.write("    	  }\r\n");
      out.write("    	}\r\n");
      out.write("    </script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("// When the user scrolls down 20px from the top of the document, show the button\r\n");
      out.write("window.onscroll = function() {scrollFunction()};\r\n");
      out.write("\r\n");
      out.write("function scrollFunction() {\r\n");
      out.write("    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\r\n");
      out.write("        document.getElementById(\"myBtn\").style.display = \"block\";\r\n");
      out.write("    } else {\r\n");
      out.write("        document.getElementById(\"myBtn\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks on the button, scroll to the top of the document\r\n");
      out.write("function topFunction() {\r\n");
      out.write("    document.body.scrollTop = 0;\r\n");
      out.write("    document.documentElement.scrollTop = 0;\r\n");
      out.write("}\r\n");
      out.write("function updateSearchUrl() {\r\n");
      out.write("    // Update the URL when the search icon is clicked\r\n");
      out.write("    window.history.replaceState({}, document.title, '/DoAnWeb/XuLyProduct');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("<style>\r\n");
      out.write("#myBtn {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	bottom: 60px;\r\n");
      out.write("	right: 0px;\r\n");
      out.write("	z-index: 99;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 2px solid #ccc;\r\n");
      out.write("	color: blue;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myBtn:hover {\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listPage {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listPage li {\r\n");
      out.write("	background-color: #ffffffBD;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listPage .active {\r\n");
      out.write("	background-color: #B192EF;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input::-webkit-calendar-picker-indicator {\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Web/Shop.jsp(97,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName == 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("		");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/Web/Shop.jsp(101,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName != 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
          out.write("\r\n");
          out.write("\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/Web/Shop.jsp(124,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/Shop.jsp(124,6) '${listProduct}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listProduct}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/Web/Shop.jsp(124,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.proname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></option>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/Web/Shop.jsp(160,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("size");
      // /WEB-INF/Web/Shop.jsp(160,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/Shop.jsp(160,3) '${sessionScope.size}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.size}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/Web/Shop.jsp(186,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/Shop.jsp(186,7) '${listCa}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listCa}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/Web/Shop.jsp(186,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<li><a class=\"text-decoration-none\"\r\n");
            out.write("									href=\"XuLyChonLocDuLieu?caid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.getCaname()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/Web/Shop.jsp(218,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/Shop.jsp(218,6) '${listProduct}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listProduct}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/Web/Shop.jsp(218,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("							<div class=\"col-md-4\">\r\n");
            out.write("								<div class=\"card mb-4 product-wap rounded-0\">\r\n");
            out.write("									<div class=\"card rounded-0\">\r\n");
            out.write("										<img style=\"width:260px;height:260px\" class=\"card-img rounded-0 img-fluid\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("										<div\r\n");
            out.write("											class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
            out.write("											<ul class=\"list-unstyled\">\r\n");
            out.write("\r\n");
            out.write("												<li><a class=\"btn btn-success text-white mt-2\"\r\n");
            out.write("													href=\"XuLyDetailProduct?productid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i\r\n");
            out.write("														class=\"far fa-eye\"></i></a></li>\r\n");
            out.write("												<li><a class=\"btn btn-success text-white mt-2\"\r\n");
            out.write("													href=\"Addtocart?productid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i\r\n");
            out.write("														class=\"fas fa-cart-plus\"></i></a></li>\r\n");
            out.write("												\r\n");
            out.write("												\r\n");
            out.write("											</ul>\r\n");
            out.write("										</div>\r\n");
            out.write("									</div>\r\n");
            out.write("									<div class=\"card-body\">\r\n");
            out.write("										<a href=\"shop-single.html\" class=\"h3 text-decoration-none\"></a>\r\n");
            out.write("										<p class=\"text-center mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.proname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("										<ul\r\n");
            out.write("											class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
            out.write("											<li class=\"pt-2\"><span\r\n");
            out.write("												class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
            out.write("												<span\r\n");
            out.write("												class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
            out.write("												<span\r\n");
            out.write("												class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
            out.write("												<span\r\n");
            out.write("												class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
            out.write("												<span\r\n");
            out.write("												class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
            out.write("											</li>\r\n");
            out.write("										</ul>\r\n");
            out.write("										<ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
            out.write("											<li><i class=\"text-warning fa fa-star\"></i> <i\r\n");
            out.write("												class=\"text-warning fa fa-star\"></i> <i\r\n");
            out.write("												class=\"text-warning fa fa-star\"></i> <i\r\n");
            out.write("												class=\"text-muted fa fa-star\"></i> <i\r\n");
            out.write("												class=\"text-muted fa fa-star\"></i></li>\r\n");
            out.write("										</ul>\r\n");
            out.write("										<p class=\"text-center mb-0\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/Web/Shop.jsp(280,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setBegin(1);
      // /WEB-INF/Web/Shop.jsp(280,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endP}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/Web/Shop.jsp(280,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <a href=\"XuLyProduct?indexs=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
