/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-30 09:19:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.User;

public final class UpdateStatusOrderTemplate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\" class=\"light-style layout-menu-fixed layout-compact\" dir=\"ltr\" data-theme=\"theme-default\"\r\n");
      out.write("  data-assets-path=\"assetsforadmin/\" data-template=\"vertical-menu-template-free\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\"\r\n");
      out.write("    content=\"width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("  <title>Update status</title>\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"description\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"assetsforadmin/img/favicon/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Fonts -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/fonts/boxicons.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/css/core.css\" class=\"template-customizer-core-css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/css/theme-default.css\" class=\"template-customizer-theme-css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/css/demo.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendors CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"assetsforadmin/vendor/libs/perfect-scrollbar/perfect-scrollbar.css\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Page CSS -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Helpers -->\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/helpers.js\"></script>\r\n");
      out.write("  <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->\r\n");
      out.write("  <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/config.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      DAO.ProductDAO dao = null;
      dao = (DAO.ProductDAO) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new DAO.ProductDAO();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <!-- Layout wrapper -->\r\n");
      out.write("  <div class=\"layout-wrapper layout-content-navbar\">\r\n");
      out.write("    <div class=\"layout-container\">\r\n");
      out.write("      <!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("      <aside id=\"layout-menu\" class=\"layout-menu menu-vertical menu bg-menu-theme\">\r\n");
      out.write("        <div class=\"app-brand demo\">\r\n");
      out.write("          <a href=\"index.html\" class=\"app-brand-link\">\r\n");
      out.write("            <span class=\"app-brand-logo demo\">\r\n");
      out.write("              <svg width=\"25\" viewBox=\"0 0 25 42\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("                <defs>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z\"\r\n");
      out.write("                    id=\"path-1\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z\"\r\n");
      out.write("                    id=\"path-3\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z\"\r\n");
      out.write("                    id=\"path-4\"></path>\r\n");
      out.write("                  <path\r\n");
      out.write("                    d=\"M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z\"\r\n");
      out.write("                    id=\"path-5\"></path>\r\n");
      out.write("                </defs>\r\n");
      out.write("                <g id=\"g-app-brand\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\r\n");
      out.write("                  <g id=\"Brand-Logo\" transform=\"translate(-27.000000, -15.000000)\">\r\n");
      out.write("                    <g id=\"Icon\" transform=\"translate(27.000000, 15.000000)\">\r\n");
      out.write("                      <g id=\"Mask\" transform=\"translate(0.000000, 8.000000)\">\r\n");
      out.write("                        <mask id=\"mask-2\" fill=\"white\">\r\n");
      out.write("                          <use xlink:href=\"#path-1\"></use>\r\n");
      out.write("                        </mask>\r\n");
      out.write("                        <use fill=\"#696cff\" xlink:href=\"#path-1\"></use>\r\n");
      out.write("                        <g id=\"Path-3\" mask=\"url(#mask-2)\">\r\n");
      out.write("                          <use fill=\"#696cff\" xlink:href=\"#path-3\"></use>\r\n");
      out.write("                          <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-3\"></use>\r\n");
      out.write("                        </g>\r\n");
      out.write("                        <g id=\"Path-4\" mask=\"url(#mask-2)\">\r\n");
      out.write("                          <use fill=\"#696cff\" xlink:href=\"#path-4\"></use>\r\n");
      out.write("                          <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-4\"></use>\r\n");
      out.write("                        </g>\r\n");
      out.write("                      </g>\r\n");
      out.write("                      <g id=\"Triangle\"\r\n");
      out.write("                        transform=\"translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) \">\r\n");
      out.write("                        <use fill=\"#696cff\" xlink:href=\"#path-5\"></use>\r\n");
      out.write("                        <use fill-opacity=\"0.2\" fill=\"#FFFFFF\" xlink:href=\"#path-5\"></use>\r\n");
      out.write("                      </g>\r\n");
      out.write("                    </g>\r\n");
      out.write("                  </g>\r\n");
      out.write("                </g>\r\n");
      out.write("              </svg>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span class=\"app-brand-text demo menu-text fw-bold ms-2\">Coffee luck</span>\r\n");
      out.write("          </a>\r\n");
      out.write("\r\n");
      out.write("          <a href=\"javascript:void(0);\" class=\"layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none\">\r\n");
      out.write("            <i class=\"bx bx-chevron-left bx-sm align-middle\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"menu-inner-shadow\"></div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"menu-inner py-1\">\r\n");
      out.write("          <!-- Dashboards -->\r\n");
      out.write("          <li class=\"menu-item active open\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-home-circle\"></i>\r\n");
      out.write("              <div data-i18n=\"Dashboards\">Home</div>\r\n");
      out.write("              <div class=\"badge bg-danger rounded-pill ms-auto\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <!-- Layouts -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!-- Front Pages -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Apps -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Pages -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-dock-top\"></i>\r\n");
      out.write("              <div data-i18n=\"Account Settings\">Account Settings</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-account.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Account\">Account</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-notifications.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Notifications\">Notifications</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"pages-account-settings-connections.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Connections\">Connections</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <!-- Components -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Forms & Tables -->\r\n");
      out.write("          <li class=\"menu-header small text-uppercase\"><span class=\"menu-header-text\">Forms &amp; Tables</span></li>\r\n");
      out.write("          <!-- Forms -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("              <div data-i18n=\"Form Elements\">Form Elements</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"forms-basic-inputs.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Basic Inputs\">Basic Inputs</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"forms-input-groups.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Input groups\">Input groups</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" class=\"menu-link menu-toggle\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-detail\"></i>\r\n");
      out.write("              <div data-i18n=\"Form Layouts\">Form Layouts</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"menu-sub\">\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"form-layouts-vertical.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Vertical Form\">Vertical Form</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-item\">\r\n");
      out.write("                <a href=\"form-layouts-horizontal.html\" class=\"menu-link\">\r\n");
      out.write("                  <div data-i18n=\"Horizontal Form\">Horizontal Form</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- Form Validation -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Tables -->\r\n");
      out.write("          <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"tables-basic.html\" class=\"menu-link\">\r\n");
      out.write("              <i class=\"menu-icon tf-icons bx bx-table\"></i>\r\n");
      out.write("              <div data-i18n=\"Tables\">Tables</div>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- Data Tables -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Misc -->\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </aside>\r\n");
      out.write("      <!-- / Menu -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Layout container -->\r\n");
      out.write("      <div class=\"layout-page\">\r\n");
      out.write("        <!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("        <nav\r\n");
      out.write("          class=\"layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme\"\r\n");
      out.write("          id=\"layout-navbar\">\r\n");
      out.write("          <div class=\"layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none\">\r\n");
      out.write("            <a class=\"nav-item nav-link px-0 me-xl-4\" href=\"javascript:void(0)\">\r\n");
      out.write("              <i class=\"bx bx-menu bx-sm\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"navbar-nav-right d-flex align-items-center\" id=\"navbar-collapse\">\r\n");
      out.write("            <!-- Search -->\r\n");
      out.write("            <div class=\"navbar-nav align-items-center\">\r\n");
      out.write("              <div class=\"nav-item d-flex align-items-center\">\r\n");
      out.write("                <i class=\"bx bx-search fs-4 lh-0\"></i>\r\n");
      out.write("                <input type=\"text\" class=\"form-control border-0 shadow-none ps-1 ps-sm-2\" placeholder=\"Search...\"\r\n");
      out.write("                  aria-label=\"Search...\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /Search -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav flex-row align-items-center ms-auto\">\r\n");
      out.write("              <!-- Place this tag where you want the button to render. -->\r\n");
      out.write("              <li class=\"nav-item lh-1 me-3\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <!-- User -->\r\n");
      out.write("              <li class=\"nav-item navbar-dropdown dropdown-user dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle hide-arrow\" href=\"javascript:void(0);\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                  <div class=\"avatar avatar-online\">\r\n");
      out.write("                    <img src=\"assetsforadmin/img/avatars/1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <div class=\"d-flex\">\r\n");
      out.write("                        <div class=\"flex-shrink-0 me-3\">\r\n");
      out.write("                          <div class=\"avatar avatar-online\">\r\n");
      out.write("                            <img src=\"assetsforadmin/img/avatars/1.png\" alt class=\"w-px-40 h-auto rounded-circle\" />\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"flex-grow-1\">\r\n");
      out.write("                          <span class=\"fw-medium d-block\">John Doe</span>\r\n");
      out.write("                          <small class=\"text-muted\">Admin</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <i class=\"bx bx-user me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">My Profile</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <i class=\"bx bx-cog me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">Settings</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                      <span class=\"d-flex align-items-center align-middle\">\r\n");
      out.write("                        <i class=\"flex-shrink-0 bx bx-credit-card me-2\"></i>\r\n");
      out.write("                        <span class=\"flex-grow-1 align-middle ms-1\">Billing</span>\r\n");
      out.write("                        <span class=\"flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20\">4</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-item\" href=\"javascript:void(0);\">\r\n");
      out.write("                      <i class=\"bx bx-power-off me-2\"></i>\r\n");
      out.write("                      <span class=\"align-middle\">Log Out</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!--/ User -->\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- / Navbar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Content wrapper -->\r\n");
      out.write("        <div class=\"content-wrapper\">\r\n");
      out.write("          <!-- Content -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"container-xxl flex-grow-1 container-p-y\">\r\n");
      out.write("            <h4 class=\"py-3 mb-4\"><span class=\"text-muted fw-light\">Account Settings /</span> Account</h4>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"nav nav-pills flex-column flex-md-row mb-3\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"javascript:void(0);\"><i class=\"bx bx-user me-1\"></i> Account</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"pages-account-settings-notifications.html\"><i class=\"bx bx-bell me-1\"></i>\r\n");
      out.write("                      Notifications</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"pages-account-settings-connections.html\"><i\r\n");
      out.write("                        class=\"bx bx-link-alt me-1\"></i> Connections</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                  <h5 class=\"card-header\">Order Details</h5>\r\n");
      out.write("                  <!-- Account -->\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"d-flex align-items-start align-items-sm-center gap-4\">\r\n");
      out.write("                      <img src=\"assetsforadmin/img/avatars/1.png\" alt=\"user-avatar\" class=\"d-block rounded\" height=\"100\"\r\n");
      out.write("                        width=\"100\" id=\"uploadedAvatar\" />\r\n");
      out.write("                      <div class=\"button-wrapper\">\r\n");
      out.write("                        <label for=\"upload\" class=\"btn btn-primary me-2 mb-4\" tabindex=\"0\">\r\n");
      out.write("                          <span class=\"d-none d-sm-block\">Upload new photo</span>\r\n");
      out.write("                          <i class=\"bx bx-upload d-block d-sm-none\"></i>\r\n");
      out.write("                          <input type=\"file\" id=\"upload\" class=\"account-file-input\" hidden\r\n");
      out.write("                            accept=\"image/png, image/jpeg\" />\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary account-image-reset mb-4\">\r\n");
      out.write("                          <i class=\"bx bx-reset d-block d-sm-none\"></i>\r\n");
      out.write("                          <span class=\"d-none d-sm-block\">Reset</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-muted mb-0\">Allowed JPG, GIF or PNG. Max size of 800K</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <hr class=\"my-0\" />\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                   <form class=\"form-horizontal\" action=\"XuLyHDOrderUpdateStatus\" method=\"post\">\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label class=\"control-label col-sm-2\" for=\"email\">ID</label>\r\n");
      out.write("      <div class=\"col-sm-10\">\r\n");
      out.write("<input type=\"text\" readonly  class=\"form-control\"  name=\"orderId\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderE.orderid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required placeholder=\"\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("    \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label class=\"control-label col-sm-2\" for=\"pwd\">Status</label>\r\n");
      out.write("      <div class=\"col-sm-10\">          \r\n");
      out.write("        <select id=\"statusorder\" class=\"form-control\" name=\"statusorder\">\r\n");
      out.write("		                <option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderR.statuscheckout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderR.statuscheckout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>    \r\n");
      out.write("		                <option value=\"Đang xử lý\">Đang xử lí</option>    \r\n");
      out.write("		                <option value=\"Đặt hàng thành công\">Đặt hàng thành công</option>    \r\n");
      out.write("		                  \r\n");
      out.write("		              </select>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   <br>\r\n");
      out.write("    <div class=\"form-group\">        \r\n");
      out.write("      <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary me-2\">Save changes</button>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-sm-offset-2 col-sm-10\" style=\"text-align:right\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- /Account -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <h5 class=\"card-header\">Delete Account</h5>\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"mb-3 col-12 mb-0\">\r\n");
      out.write("                      <div class=\"alert alert-warning\">\r\n");
      out.write("                        <h6 class=\"alert-heading mb-1\">Are you sure you want to delete your account?</h6>\r\n");
      out.write("                        <p class=\"mb-0\">Once you delete your account, there is no going back. Please be certain.</p>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form id=\"formAccountDeactivation\" onsubmit=\"return false\">\r\n");
      out.write("                      <div class=\"form-check mb-3\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" name=\"accountActivation\"\r\n");
      out.write("                          id=\"accountActivation\" />\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"accountActivation\">I confirm my account\r\n");
      out.write("                          deactivation</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-danger deactivate-account\">Deactivate Account</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- / Content -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Footer -->\r\n");
      out.write("          <footer class=\"content-footer footer bg-footer-theme\">\r\n");
      out.write("            <div class=\"container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column\">\r\n");
      out.write("              <div class=\"mb-2 mb-md-0\">\r\n");
      out.write("                ©\r\n");
      out.write("                <script>\r\n");
      out.write("                  document.write(new Date().getFullYear());\r\n");
      out.write("                </script>\r\n");
      out.write("                , made with ❤️ by\r\n");
      out.write("                <a href=\"https://themeselection.com\" target=\"_blank\" class=\"footer-link fw-medium\">ThemeSelection</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"d-none d-lg-inline-block\">\r\n");
      out.write("                <a href=\"https://themeselection.com/license/\" class=\"footer-link me-4\" target=\"_blank\">License</a>\r\n");
      out.write("                <a href=\"https://themeselection.com/\" target=\"_blank\" class=\"footer-link me-4\">More Themes</a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation/\"\r\n");
      out.write("                  target=\"_blank\" class=\"footer-link me-4\">Documentation</a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"https://github.com/themeselection/sneat-html-admin-template-free/issues\" target=\"_blank\"\r\n");
      out.write("                  class=\"footer-link\">Support</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </footer>\r\n");
      out.write("          <!-- / Footer -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"content-backdrop fade\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Content wrapper -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / Layout page -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Overlay -->\r\n");
      out.write("    <div class=\"layout-overlay layout-menu-toggle\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- / Layout wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"buy-now\">\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Core JS -->\r\n");
      out.write("  <!-- build:js assets/vendor/js/core.js -->\r\n");
      out.write("\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/jquery/jquery.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/popper/popper.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/bootstrap.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/libs/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("  <script src=\"assetsforadmin/vendor/js/menu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- endbuild -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendors JS -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main JS -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page JS -->\r\n");
      out.write("  <script src=\"assetsforadmin/js/pages-account-settings-account.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Place this tag in your head or just before your close body tag. -->\r\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/Web/UpdateStatusOrderTemplate.jsp(50,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("productE");
      // /WEB-INF/Web/UpdateStatusOrderTemplate.jsp(50,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/Web/UpdateStatusOrderTemplate.jsp(50,0) '${dao.getAllProductById(param.editproductid)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dao.getAllProductById(param.editproductid)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/Web/UpdateStatusOrderTemplate.jsp(243,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.userloginA.name}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<p style=\"position:relative;top:8px\">Chào ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userloginA.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/<a href=\"DangNhap.jsp\" style=\"text-decoration:none\">LogOut</a></p>    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <a href=\"DangNhap.jsp\" style=\"text-decoration:none\">Log in</a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
