/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-01-22 04:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.*;
import Model.*;
import java.util.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/LTWebCuoiKy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DoAnWeb/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702995907573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DAO");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	
    KhachHang auth = (KhachHang) request.getSession().getAttribute("user");
	List<Order> orders = null;
	if (auth != null) {
	    request.setAttribute("person", auth);
	    OrderDAO orderDao  = new OrderDAO();
		orders = orderDao.getAllOrder(auth.getUserName(), 0);
	}else{
		response.sendRedirect("login.jsp");
	}
	ArrayList<Cart> cart_list = (ArrayList<Cart>) session.getAttribute("cart-list");
	if (cart_list != null) {
		request.setAttribute("cart_list", cart_list);
	}
	
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>CheckOut</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome.min.css\">\r\n");
      out.write("          <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- Start Top Nav -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block\" id=\"templatemo_nav_top\">\r\n");
      out.write("        <div class=\"container text-light\">\r\n");
      out.write("            <div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <i class=\"fa fa-envelope mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"\r\n");
      out.write("                      href=\"mailto:info@company.com\">info@company.com</a>\r\n");
      out.write("                    <i class=\"fa fa-phone mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://fb.com/templatemo\" target=\"_blank\" rel=\"sponsored\"><i\r\n");
      out.write("                          class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.linkedin.com/\" target=\"_blank\"><i\r\n");
      out.write("                          class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("      aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("            <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("                <div class=\"input-group mb-2\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                    <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("            \r\n");
      out.write("    		<!-- Start Hero Section -->\r\n");
      out.write("			<section class=\"bg-success py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-5\">\r\n");
      out.write("                <div class=\"col-md-8 text-white\">\r\n");
      out.write("                    <h1>Billing details</h1>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <br>\r\n");
      out.write("		<!-- End Hero Section -->\r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("    <form action=\"XuLyThanhToan?&username=");
      out.print(auth.getUserName() );
      out.write("\" method=\"post\">\r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("		        <div class=\"col-md-6 mb-5 mb-md-0\">\r\n");
      out.write("		          <h2 class=\"h3 mb-3 text-black\">Billing Details</h2>\r\n");
      out.write("		          <div class=\"p-3 p-lg-5 border bg-white\">\r\n");
      out.write("		            <div class=\"form-group\">\r\n");
      out.write("		              <label for=\"c_country\" class=\"text-black\">Country <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		              <select id=\"c_country\" class=\"form-control\" name=\"c_country\">\r\n");
      out.write("		                <option value=\"1\">Select a country</option>    \r\n");
      out.write("		                <option value=\"Vietnam\">Vietnam</option>    \r\n");
      out.write("		                <option value=\"Algeria\">Algeria</option>    \r\n");
      out.write("		                <option value=\"Afghanistan\">Afghanistan</option>    \r\n");
      out.write("		                <option value=\"America\">America</option>    \r\n");
      out.write("		                <option value=\"UK\">UK</option>    \r\n");
      out.write("		                <option value=\"India\">India</option>    \r\n");
      out.write("		                <option value=\"Japan\">Japan</option>    \r\n");
      out.write("		                <option value=\"Korea\">Korea</option>    \r\n");
      out.write("		              </select>\r\n");
      out.write("		            </div>\r\n");
      out.write("		            <div class=\"form-group row\">\r\n");
      out.write("		              <div class=\"col-md-6\">\r\n");
      out.write("		                <label for=\"c_fname\" class=\"text-black\">First Name <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_fname\" name=\"c_fname\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"col-md-6\">\r\n");
      out.write("		                <label for=\"c_lname\" class=\"text-black\">Last Name <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_lname\" name=\"c_lname\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("		            <div class=\"form-group row\">\r\n");
      out.write("		              <div class=\"col-md-12\">\r\n");
      out.write("		                <label for=\"c_companyname\" class=\"text-black\">Company Name </label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_companyname\" name=\"c_companyname\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("		            <div class=\"form-group row\">\r\n");
      out.write("		              <div class=\"col-md-12\">\r\n");
      out.write("		                <label for=\"c_address\" class=\"text-black\">Address <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_address\" name=\"c_address\" placeholder=\"Street address\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("		           \r\n");
      out.write("\r\n");
      out.write("		          \r\n");
      out.write("\r\n");
      out.write("		            <div class=\"form-group row mb-5\">\r\n");
      out.write("		              <div class=\"col-md-6\">\r\n");
      out.write("		                <label for=\"c_email_address\" class=\"text-black\">Email Address <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_email_address\" name=\"c_email_address\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"col-md-6\">\r\n");
      out.write("		                <label for=\"c_phone\" class=\"text-black\">Phone <span class=\"text-danger\">*</span></label>\r\n");
      out.write("		                <input type=\"text\" class=\"form-control\" id=\"c_phone\" name=\"c_phone\" placeholder=\"Phone Number\">\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("		            <div class=\"form-group\">\r\n");
      out.write("		              <div class=\"collapse\" id=\"create_an_account\">\r\n");
      out.write("		                <div class=\"py-2 mb-4\">\r\n");
      out.write("		                  <p class=\"mb-3\">Create an account by entering the information below. If you are a returning customer please login at the top of the page.</p>\r\n");
      out.write("		                  <div class=\"form-group\">\r\n");
      out.write("		                    <label for=\"c_account_password\" class=\"text-black\">Account Password</label>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("		            \r\n");
      out.write("		            <div class=\"form-group\">\r\n");
      out.write("		              <label for=\"c_order_notes\" class=\"text-black\">Order Notes</label>\r\n");
      out.write("		              <textarea name=\"c_order_notes\" id=\"c_order_notes\" cols=\"30\" rows=\"5\" class=\"form-control\" placeholder=\"Write your notes here...\"></textarea>\r\n");
      out.write("		            </div>\r\n");
      out.write("\r\n");
      out.write("		          </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        <div class=\"col-md-6\">\r\n");
      out.write("\r\n");
      out.write("		          <div class=\"row mb-5\">\r\n");
      out.write("		            <div class=\"col-md-12\">\r\n");
      out.write("		              <h2 class=\"h3 mb-3 text-black\">Coupon Code</h2>\r\n");
      out.write("		              <div class=\"p-3 p-lg-5 border bg-white\">\r\n");
      out.write("\r\n");
      out.write("		                <label for=\"c_code\" class=\"text-black mb-3\">Enter your coupon code if you have one</label>\r\n");
      out.write("		                <div class=\"input-group w-75 couponcode-wrap\">\r\n");
      out.write("		                  <input type=\"text\" class=\"form-control me-2\" id=\"c_code\" placeholder=\"Coupon Code\" aria-label=\"Coupon Code\" aria-describedby=\"button-addon2\">\r\n");
      out.write("		                  <div class=\"input-group-append\">\r\n");
      out.write("		                    <button class=\"btn btn-black btn-sm\" type=\"button\" id=\"button-addon2\">Apply</button>\r\n");
      out.write("		                  </div>\r\n");
      out.write("		                </div>\r\n");
      out.write("\r\n");
      out.write("		              </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		          </div>\r\n");
      out.write("\r\n");
      out.write("		          <div class=\"row mb-5\">\r\n");
      out.write("		            <div class=\"col-md-12\">\r\n");
      out.write("		              <h2 class=\"h3 mb-3 text-black\">Your Order</h2>\r\n");
      out.write("		              <div class=\"p-3 p-lg-5 border bg-white\">\r\n");
      out.write("		                <table class=\"table site-block-order-table mb-5\">\r\n");
      out.write("		                  <thead>\r\n");
      out.write("		                  <tr>\r\n");
      out.write("		                    <th scope=\"col\">Date</th>\r\n");
      out.write("					<th scope=\"col\">Detail</th>\r\n");
      out.write("					<th scope=\"col\">Cancel</th>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("		                  </thead>\r\n");
      out.write("		                  <tbody>\r\n");
      out.write("		                   ");

			if(orders != null){
				for(Order o:orders){
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>");
      out.print(o.getDate());
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(o.productname );
      out.write('|');
      out.print(o.quantity );
      out.write('x');
      out.print(o.prices );
      out.write("</td>\r\n");
      out.write("						<td><a class=\"btn btn-sm btn-danger\" href=\"XuLyXoaOrder?id=");
      out.print(o.getOrderid());
      out.write("&username=");
      out.print(auth.getUserName() );
      out.write("\">Cancel Order</a></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				");
}
			}
			
      out.write("\r\n");
      out.write("		                  </tbody>\r\n");
      out.write("		                </table>\r\n");
      out.write("		                <a class=\"btn btn-sm btn-danger\" href=\"XuLyXoaAllOrder?&username=");
      out.print(auth.getUserName() );
      out.write("\">Cancel all Order</a>\r\n");
      out.write("\r\n");
      out.write("		                <div class=\"border p-3 mb-3\">\r\n");
      out.write("        <input type=\"radio\" name=\"paymentMethod\" id=\"directBankTransferCheckbox\" value=\"DirectBankTransfer\">\r\n");
      out.write("       <span style=\"font-size:20px\">Direct Bank Transfer</span>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("  \r\n");
      out.write("        <input type=\"radio\" name=\"paymentMethod\" id=\"chequePaymentCheckbox\" value=\"Cast\">\r\n");
      out.write("            <span style=\"font-size:20px\">Cast</span>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		            </div>\r\n");
      out.write("		       \r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm btn-danger\" ><span style=\"font-size:20px\">Place order</span></button>\r\n");
      out.write("\r\n");
      out.write("		        </div>\r\n");
      out.write("		      </div>\r\n");
      out.write("		      <!-- </form> -->\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /checkout.jsp(77,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName == 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "HeaderAdmin.jsp", out, false);
          out.write("\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /checkout.jsp(81,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName != 'PTT'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
          out.write("\r\n");
          out.write("    \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
